# Generated by Django 5.2.1 on 2026-06-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='nazov')),
                ('short_title', models.CharField(blank=True, max_length=90, verbose_name='kratky nazov')),
                ('description', models.TextField(verbose_name='popis')),
                ('image_path', models.CharField(help_text='Napriklad: home/vendor/Images/oc-uvod-01.jpg', max_length=255, verbose_name='cesta k obrazku v static')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='vytvorene')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravene')),
            ],
            options={
                'verbose_name': 'sluzba',
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
                'ordering': ['order', 'id'],
            },
        ),
    ]
