# Generated by Django 5.2.1 on 2026-06-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='nadpis')),
                ('subtitle', models.CharField(max_length=220, verbose_name='podnadpis')),
                ('intro', models.TextField(verbose_name='uvodny text')),
                ('cta_text', models.CharField(default='Poziadat o cenovu ponuku', max_length=80, verbose_name='text hlavneho tlacidla')),
                ('cta_url', models.CharField(default='#kontakt', max_length=160, verbose_name='odkaz hlavneho tlacidla')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('contact_text', models.TextField(blank=True, verbose_name='kontaktna vyzva')),
                ('seo_title', models.CharField(blank=True, max_length=160, verbose_name='SEO titulok')),
                ('meta_description', models.CharField(blank=True, max_length=220, verbose_name='meta popis')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivna titulna stranka')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='upravene')),
            ],
            options={
                'verbose_name': 'titulna stranka',
                'verbose_name_plural': 'titulna stranka',
            },
        ),
        migrations.CreateModel(
            name='HomePageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('services', 'Sluzby'), ('benefits', 'Vyhody'), ('process', 'Priebeh realizacie')], max_length=20, verbose_name='sekcia')),
                ('title', models.CharField(max_length=120, verbose_name='nadpis')),
                ('description', models.TextField(verbose_name='popis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivne')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homepage', verbose_name='titulna stranka')),
            ],
            options={
                'verbose_name': 'polozka titulnej stranky',
                'verbose_name_plural': 'polozky titulnej stranky',
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
