# Generated by Django 6.0.6 on 2026-07-01 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.FileField(blank=True, help_text='Volitelny obrazok sluzby. Ak nie je vyplneny, pouzije sa povodna cesta v static.', upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='obrazok'),
        ),
    ]
