# Generated by Django 6.0.6 on 2026-07-01 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(blank=True, help_text='Volitelny obrazok sluzby. Ak nie je vyplneny, pouzije sa default obrazok.', upload_to='services/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='obrazok'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image_path',
            field=models.CharField(blank=True, default='home/vendor/Images/oc-uvod-01.jpg', editable=False, max_length=255, verbose_name='cesta k obrazku v static'),
        ),
    ]
